### ISSUE TITLE
update

### ISSUE THREAD

**Issue by bambinidk** [iamceph/LampControl#2]
please update this plugin for 12.2 and up. Because its a great plugin. It dont work for 12.2 and up

**Comment by iamceph** [comment]
I did not had time to finish update. Check dev branch,  I'll try to finish it today :)

**Comment by iamceph** [comment]
[lampcontrol.zip](https://github.com/iamceph/LampControl/files/2613452/lampcontrol.zip)

Please try this version on 1.13 :)

**Comment by iamceph** [comment]
Updated to 1.13, please check Spigot forums for more.
