### ISSUE TITLE
Furnaces

### ISSUE THREAD

**Issue by Kikisito** [iamceph/LampControl#3]
Hello, after using LampControl for 1.13.2, some blocks like furnaces, can be enabled or disabled by clicking them with the hand or, in this case, flint and steel, and its content is erased. Can you fix this?

**Comment by iamceph** [comment]
Hello, I saw that on Spigot. Any errors in log or so?

**Comment by Kikisito** [comment]
Nothing

**Comment by iamceph** [comment]
Okay, got the problem. Working on it! Will be fixed tomorrow :)

**Comment by iamceph** [comment]
Fixed in new update, please check spigot.

**Comment by Kikisito** [comment]
Thank you!
