### ISSUE TITLE
Error LC3.1 1.13.2

### ISSUE THREAD

**Issue by Elvi81** [iamceph/LampControl#4]
3.0 works beter than 3.1 on spigot 1.13.2
https://pastebin.com/dt2G5VVD

**Comment by Elvi81** [comment]
Edit: none of the versions on bukkit 3.1-dev nor 3.1.1 on spigot work properly if for instance you click a powered rail nothing happens except the error in the console, redstone lamps seems to work tho but still errors.

**Comment by iamceph** [comment]
Do you use latest version? Can you please specify the actions you doing and put me full log? Thanks
3.1.1 is still work in progress, so there can be some errors

**Comment by iamceph** [comment]
I found the problem, my bad. Will be fixed in new build by tomorrow :) Please understand that 3.1 is complete rewrite of this plugin so there can be issues at all. Thanks for reporting!

**Comment by Elvi81** [comment]
Where would i get that new build then? cause you don't have a link to any dev builds at all.

**Comment by iamceph** [comment]
[lampcontrol_3.1.2_dev.zip](https://github.com/iamceph/LampControl/files/2654286/lampcontrol_3.1.2_dev.zip)
Here :)

**Comment by iamceph** [comment]
Just testing all and found another problems, so working on it right now

**Comment by Elvi81** [comment]
I hear clicks on powered rails but it does not change states.

And redstone lamps cause these errors and does not change states either.
https://pastebin.com/w0J5JngZ

config.yml
https://pastebin.com/WxC2GfJX

**Comment by iamceph** [comment]
I see the problem, I will upload here fixed version. Thanks!

**Comment by iamceph** [comment]
Hello, can you please test this version? I will get to fix the rails today, sorry for the delay.
[lampcontrol-3.1.2.zip](https://github.com/iamceph/LampControl/files/2659973/lampcontrol-3.1.2.zip)

**Comment by Elvi81** [comment]
No errors from what i can see, can turn on/off redstone lamps with rightclick but buttons or levers have no effect on them.

**Comment by iamceph** [comment]
Just fixed it. I will post new update on spigot today

**Comment by iamceph** [comment]
New version is released

**Comment by Elvi81** [comment]
Think you might have uploaded the wrong version on spigot as i get a 3.1.1 version and rightclicking on powered rails don't work + error.
https://pastebin.com/qjkQsQUT

**Comment by Elvi81** [comment]
Still erroring on 3.1.2, this time by just clicking air.
https://pastebin.com/H0yAf5XV

**Comment by iamceph** [comment]
Hello, is this issue still pretend?

**Comment by Elvi81** [comment]
I think the current version is doing ok, have not checked that much lately.

**Comment by iamceph** [comment]
I really did not had any time to sort all stuff out, sorry for that. If you'll have some time, can you check it out? :)

**Comment by Elvi81** [comment]
Sort what out? i'm not a programmer.

**Comment by iamceph** [comment]
Oh I mean, I did not had time to reach you back

**Comment by Elvi81** [comment]
Just tested with the latest build of spigot, works fine, both rails and lamps turn off and on with no errors.
